/** Auto-generated by scripts/optimize-management-images.mjs — do not edit manually */
export type LeadershipImageVariant = {
  width: number;
  src: string;
  bytes: number;
};

export type LeadershipImageAsset = {
  slug: string;
  original: string;
  alt: string;
  aspectRatio: "4/5";
  defaultWidth: number;
  defaultHeight: number;
  variants: LeadershipImageVariant[];
};

export const LEADERSHIP_IMAGES = {
  "karol-kemp": {
    "slug": "karol-kemp",
    "original": "/images/mgt/Karol-Kemp.png",
    "alt": "Karol Kemp, Founder and Chief Executive Officer of Alto Rich",
    "aspectRatio": "4/5",
    "defaultWidth": 800,
    "defaultHeight": 1000,
    "variants": [
      {
        "width": 320,
        "src": "/images/mgt/optimized/karol-kemp-320.webp",
        "bytes": 13832
      },
      {
        "width": 480,
        "src": "/images/mgt/optimized/karol-kemp-480.webp",
        "bytes": 26734
      },
      {
        "width": 640,
        "src": "/images/mgt/optimized/karol-kemp-640.webp",
        "bytes": 43656
      },
      {
        "width": 800,
        "src": "/images/mgt/optimized/karol-kemp-800.webp",
        "bytes": 63880
      },
      {
        "width": 960,
        "src": "/images/mgt/optimized/karol-kemp-960.webp",
        "bytes": 78564
      }
    ]
  },
  "olaniyi-adeyemo": {
    "slug": "olaniyi-adeyemo",
    "original": "/images/mgt/Olaniyi-Adeyemo.png",
    "alt": "Olaniyi Adeyemo, Executive Director Operations and Member Success at Alto Rich",
    "aspectRatio": "4/5",
    "defaultWidth": 800,
    "defaultHeight": 1000,
    "variants": [
      {
        "width": 320,
        "src": "/images/mgt/optimized/olaniyi-adeyemo-320.webp",
        "bytes": 10212
      },
      {
        "width": 480,
        "src": "/images/mgt/optimized/olaniyi-adeyemo-480.webp",
        "bytes": 19924
      },
      {
        "width": 640,
        "src": "/images/mgt/optimized/olaniyi-adeyemo-640.webp",
        "bytes": 34838
      },
      {
        "width": 800,
        "src": "/images/mgt/optimized/olaniyi-adeyemo-800.webp",
        "bytes": 54696
      },
      {
        "width": 960,
        "src": "/images/mgt/optimized/olaniyi-adeyemo-960.webp",
        "bytes": 67826
      }
    ]
  },
  "tamunotonye-peterside": {
    "slug": "tamunotonye-peterside",
    "original": "/images/mgt/Tamunotonye-Peterside.png",
    "alt": "Tamunotonye Peterside, Regional Director Business Development at Alto Rich",
    "aspectRatio": "4/5",
    "defaultWidth": 800,
    "defaultHeight": 1000,
    "variants": [
      {
        "width": 320,
        "src": "/images/mgt/optimized/tamunotonye-peterside-320.webp",
        "bytes": 7850
      },
      {
        "width": 480,
        "src": "/images/mgt/optimized/tamunotonye-peterside-480.webp",
        "bytes": 13890
      },
      {
        "width": 640,
        "src": "/images/mgt/optimized/tamunotonye-peterside-640.webp",
        "bytes": 21116
      },
      {
        "width": 800,
        "src": "/images/mgt/optimized/tamunotonye-peterside-800.webp",
        "bytes": 29876
      },
      {
        "width": 960,
        "src": "/images/mgt/optimized/tamunotonye-peterside-960.webp",
        "bytes": 38480
      }
    ]
  },
  "abubakar-nasir": {
    "slug": "abubakar-nasir",
    "original": "/images/mgt/Abubakar-Nasir.png",
    "alt": "Abubakar Nasir, Regional Director Government and Institutional Relations at Alto Rich",
    "aspectRatio": "4/5",
    "defaultWidth": 800,
    "defaultHeight": 1000,
    "variants": [
      {
        "width": 320,
        "src": "/images/mgt/optimized/abubakar-nasir-320.webp",
        "bytes": 13148
      },
      {
        "width": 480,
        "src": "/images/mgt/optimized/abubakar-nasir-480.webp",
        "bytes": 27272
      },
      {
        "width": 640,
        "src": "/images/mgt/optimized/abubakar-nasir-640.webp",
        "bytes": 45576
      },
      {
        "width": 800,
        "src": "/images/mgt/optimized/abubakar-nasir-800.webp",
        "bytes": 66658
      },
      {
        "width": 960,
        "src": "/images/mgt/optimized/abubakar-nasir-960.webp",
        "bytes": 82096
      }
    ]
  }
} as const satisfies Record<string, LeadershipImageAsset>;

export type LeadershipImageSlug = keyof typeof LEADERSHIP_IMAGES;
